import { Kysely } from 'kysely';

import type { DB } from '@/types/kysely-codegen';

/**
 * Database class extends Kysely to provide a type-safe interface for database operations.
 * It is configured with the DB type generated by Kysely code generation.
 */
export class Database extends Kysely<DB> {
  // Additional methods or properties can be added here if needed
}
